### ISSUE TITLE
 TS2307: Cannot find module '@apollo/gateway' or its corresponding type declarations. - came back

### ISSUE THREAD

**Issue by razorness** [nestjs/graphql#1028]
## I'm submitting a...

<pre><code>
[ ] Regression 
[X] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead post your question on Stack Overflow.
</code></pre>

## Current behavior

Same error as fixed for #992 found its way back to current release.

```
"C:\Program Files\nodejs\node.exe" C:\Users\xxx\AppData\Roaming\npm\node_modules\yarn\bin\yarn.js run start:dev
[16:47:50] Starting compilation in watch mode...

node_modules/@nestjs/graphql/dist/interfaces/gql-gateway-module-options.interface.d.ts:1:58 - error TS2307: Cannot find module '@apollo/gateway' or its corresponding type declarations.

1 import { GatewayConfig, ServiceEndpointDefinition } from '@apollo/gateway';
                                                           ~~~~~~~~~~~~~~~~~

node_modules/@nestjs/graphql/dist/interfaces/gql-gateway-module-options.interface.d.ts:2:35 - error TS2307: Cannot find module '@apollo/gateway/src/datasources/types' or its corresponding type declarations.

2 import { GraphQLDataSource } from '@apollo/gateway/src/datasources/types';
                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

[16:47:56] Found 2 errors. Watching for file changes.
```

## Environment

<pre><code>
$ nest info

 _   _             _      ___  _____  _____  _     _____
| \ | |           | |    |_  |/  ___|/  __ \| |   |_   _|
|  \| |  ___  ___ | |_     | |\ `--. | /  \/| |     | |
| . ` | / _ \/ __|| __|    | | `--. \| |    | |     | |
| |\  ||  __/\__ \| |_ /\__/ //\__/ /| \__/\| |_____| |_
\_| \_/ \___||___/ \__|\____/ \____/  \____/\_____/\___/

[System Information]
OS Version     : Windows 10
NodeJS Version : v12.16.3
YARN Version    : 1.22.4

[Nest CLI]
Nest CLI Version : 7.4.1

[Nest Platform Information]
platform-express version : 7.2.0
elasticsearch version    : 7.1.0
passport version         : 7.0.0
graphql version          : 7.5.3
typeorm version          : 7.1.0
common version           : 7.2.0
core version             : 7.2.0
</code></pre>

## Last working version
`v7.5.1` 

## Possible solution
Revert https://github.com/nestjs/graphql/commit/58def406aa412848e5cfea39585e2eb3e0d7477c#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L78

**Comment by kamilmysliwiec** [comment]
Fixed in 7.5.5

**Comment by razorness** [comment]
Can confirm, it's fixed in `v7.5.5`. Thanks!

**Comment by pavankumarkatakam** [comment]
Im still getting this error in 7.5.5 please check below screenshot
![nest_error](https://user-images.githubusercontent.com/6078669/87533554-6ccbdf00-c6b2-11ea-92e7-fbd30d217100.png)

**Comment by razorness** [comment]
@pavankumarkatakam Please make sure to use current NodeJS LTS `v12.x.x` and Typescript `v3.9.x`.
I look likes there is an odd side effect when using older versions of NodeJS. Most people get rid of this after updating. See https://github.com/nestjs/graphql/issues/992#issuecomment-654469180.

**Comment by pavankumarkatakam** [comment]
Thank @razorness, after changing the node version to 12 it is working fine.
