### ISSUE TITLE
Nest can't resolve dependencies of the ApolloDriver

### ISSUE THREAD

**Issue by alexopenkowski-the-nu-company** [nestjs/graphql#2031]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I followed the migration guide for "Migrating to v10". This is how my `GraphQLModule.forRootAsync` config now looks:

```
import { Module } from "@nestjs/common"
import { AuthModule } from "./auth/auth.module"
import { AppConfigModule } from "./config/app-config.module"
import { GraphQLModule } from "@nestjs/graphql"
import { ApolloDriver, ApolloDriverConfig } from "@nestjs/apollo"
import { AppConfigService } from "./config/app-config.service"
import { join } from "path"

@Module({
	imports: [
		AppConfigModule,
		AuthModule,
		GraphQLModule.forRootAsync<ApolloDriverConfig>({
			driver: ApolloDriver,
			imports: [AppConfigModule],
			inject: [AppConfigService],
			useFactory: (appConfig: AppConfigService) => ({
				debug: appConfig.get.graphql.debug,
				playground: appConfig.get.graphql.playground,
				autoSchemaFile: join(process.cwd(), "src/graphql/schema.gql"),
				cors: appConfig.get.cors,
			}),
		}),
	],
})
export class AppModule {}
```

I keep seeing the following error:

```
[Nest] 19201  - 02/19/2022, 8:45:24 AM   ERROR [ExceptionHandler] Nest can't resolve dependencies of the ApolloDriver (?). Please make sure that the argument ModulesContainer at index [0] is available in the GraphQLModule context.

Potential solutions:
- If ModulesContainer is a provider, is it part of the current GraphQLModule?
- If ModulesContainer is exported from a separate @Module, is that module imported within GraphQLModule?
  @Module({
    imports: [ /* the Module containing ModulesContainer */ ]
  })

Error: Nest can't resolve dependencies of the ApolloDriver (?). Please make sure that the argument ModulesContainer at index [0] is available in the GraphQLModule context.

Potential solutions:
- If ModulesContainer is a provider, is it part of the current GraphQLModule?
- If ModulesContainer is exported from a separate @Module, is that module imported within GraphQLModule?
  @Module({
    imports: [ /* the Module containing ModulesContainer */ ]
  })
```

### Minimum reproduction code

[reproduce-apollo-driver-dependencies-issue](https://github.com/alexopenkowski-the-nu-company/reproduce-apollo-driver-dependencies-issue)

### Steps to reproduce

- `yarn install`
- `yarn workspace api dev`

### Expected behavior

Application starts and GraphQL API is working as with V9.

### Package version

"@nestjs/graphql": "10.0.4"

### Graphql version

"graphql": "16.3.0"

### NestJS version

"@nestjs/core": "8.3.1"

"@nestjs/common": "8.3.1",
"@nestjs/config": "1.2.0",
"@nestjs/apollo": "10.0.4",
"@nestjs/platform-express": "8.3.1",
"apollo-server-express": "3.6.3",

### Node.js version

v16.13.1

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Other

Yarn Workspaces

**Comment by jmcdo29** [comment]
Please provide a [minimum reproduction repository](http://minimum-reproduction.wtf).

**Comment by alexopenkowski-the-nu-company** [comment]
Will do ASAP.

**Comment by alexopenkowski-the-nu-company** [comment]
Here it is: [reproduce-apollo-driver-dependencies-issue](https://github.com/alexopenkowski-the-nu-company/reproduce-apollo-driver-dependencies-issue)

I also tried to follow the docs for `forRootAsync` in two versions, but both don't compile:
- https://github.com/alexopenkowski-the-nu-company/reproduce-apollo-driver-dependencies-issue/tree/async-options-trouble
- https://github.com/alexopenkowski-the-nu-company/reproduce-apollo-driver-dependencies-issue/tree/async-options-trouble-2

Let me know if I can help further or if I'm just being stupid. :)

**Comment by jmcdo29** [comment]
It looks like `yarn workspace` and the `yarn install` command aren't respecting what should be happening with the dependencies. [yarn's docs on `nohoist`](https://classic.yarnpkg.com/blog/2018/02/15/nohoist/) show that there _should_ only be one version of `node_modules` are the workspace root. However, that's not the case here, and you're getting two installed versions of your `@nestjs/*` packages, which causes these errors to arise due to JavaScript Object Equality checks failing when classes come from different locations. Basically `FooA` and `FooB` have **exactly** the same properties, formatting, everything, but `FooA === FooB` is false.

**Comment by alexopenkowski-the-nu-company** [comment]
We only recently started using Yarn Workspaces and I did not even know of this `nohoist` option! Thank you so much, I could fix/workaround the issue by using `nohoist` in the root `package.json`: 

```
"workspaces": {
	"packages": [
		"api"
	],
	"nohoist": ["**/@nestjs", "**/@nestjs/**"]
},
```

https://github.com/alexopenkowski-the-nu-company/reproduce-apollo-driver-dependencies-issue/commit/0b9c10923a59d1948914633e051150baa309f944

So I'm actually happy already, but still curious: Can we explain why this duplicate `@nestjs/*` packages thing happens? Is it an issue with our setup or with NestJS or even with Yarn?

**Comment by jmcdo29** [comment]
No clue why the duplicates were happening when you added in `@nestjs/apollo` and upgraded `@nestjs/graphql` to v10. I assume it has something to do with yarn and the yarn workspace (which is why I usually advocate for nx as a monorepo management tool). Glad the nohoist option worked for you though

**Comment by kamilmysliwiec** [comment]
I think this might have been caused by missing `@nestjs/graphql` entry in `@nestjs/apollo` peer dependencies. I have fixed it here https://github.com/nestjs/graphql/commit/4687c89e4b6e519dfb26c3b69003a915a7f561ba. My suspect is that Yarn analyzed `@nestjs/apollo` peer deps and noticed `@nestjs/graphql` wasn't listed there and so they didn't necessarily have to leave in the same `node_modules` folder. One was auto-hoisted then (hence the error).

**Comment by alexopenkowski-the-nu-company** [comment]
Thanks, I will report back if we can go w/o the `nohoist` setting as soon as this is released.

**Comment by makbari** [comment]
This error is still happens. 
`"@nestjs/graphql": "^10.0.6",`
`"@nestjs/apollo": "^10.0.6",`

Same scenario. 
Lerna + yarn workspaces setup.

**Comment by kamilmysliwiec** [comment]
@makbari Please create a separate issue with the minimum reproduction repository.
