### ISSUE TITLE
resolveType on unions and itnerface from type-graphql ignored when using code first approach

### ISSUE THREAD

**Issue by vnenkpet** [nestjs/graphql#231]
**Describe the bug**
When I try defining a resolveType function on createUnionType, it compiles succesfully but I'm getting this warning: 

```
Type "MyUnionType" is missing a "__resolveType" resolver. Pass false into "resolverValidationOptions.requireResolversForResolveType" to disable this warning.
```

The type then really isn't working and complains with this: 
```
Abstract type MyUnionType must resolve to an Object type at runtime for field UserType.myUnion (...)
```

**To Reproduce**
```
export const MyUnionType = createUnionType({
  name: 'MyUnionType',
  types: [PersonType, PlaceType],
  resolveType: value => {
    if (value instanceof PersonEntity) {
      return PersonType;
    }
    if (value instanceof PlaceEntity) {
      return PlaceType;
    }
    return undefined;
  },
});
```
(I didn't test if the resolveType method itself works properly, but that's unrelated to this issue as it's obviously ignored - definitely doesn't get called).

**Expected behavior**
This should work and resolve into the proper type at runtime. 

**Enviorment**
 - OS: MacOS
 - Node 12.1.0
 - Package version 0.17.3
 - TypeScript version 3.4.2
- @nestjs/graphql version 6.0.5

**Comment by vnenkpet** [comment]
Asked in https://github.com/19majkel94/type-graphql/issues/326 already, apparently out of their scope so I suppose it belongs here. It's a new feature in type-graphql but I think it would be nice to have it here.

**Comment by kamilmysliwiec** [comment]
It should be fixed in the @next version (`$ npm i @nestjs/graphql@next`). You will also have to update `@nestjs/core` to 6.2.0 (`$ npm i @nestjs/core@6.2.0`)

**Comment by kamilmysliwiec** [comment]
Published as `6.2.0` (`$ npm i @nestjs/graphql@latest`). You will also have to update `@nestjs/core` to 6.2.0 (`$ npm i @nestjs/core@latest`)

**Comment by pereslavtsev** [comment]
@kamilmysliwiec still reproducible, I have version @nestjs/graphql 6.4.3 and type-graphql 0.17.5 (latest)

**Comment by Logic-Bits** [comment]
can confirm - CustomFieldConfigUnion doesnt work.
in my case the unionMetadata.classTypes is empty and throws error at buildTypesInfo() in schema-generator.js

**Comment by JazzShapka** [comment]
resolveType for createUnionType still doesn't work. Are there any other solutions?
