### ISSUE TITLE
Error: Abstract methods can only appear within an abstract class

### ISSUE THREAD

**Issue by biryukvy** [nestjs/graphql#99]
## I'm submitting a...

<pre><code>
[ ] Regression 
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead post your question on Stack Overflow.
</code></pre>

## Current behavior

1. Define parameters in property of the type, like this:
```
type Cat {
  ...
  food(brand: String): [Food]
}
```
2. Restart your server to apply changes. This will add the abstract method to the class of the type in _src/graphql.schema.ts_:
```
export class Cat {
    ...
    abstract food(brand?: string): Food[] | Promise<Food[]>;
}
```
3. Restart server (to apply any other changes, for example) and you will get the error:
> TSError: ⨯ Unable to compile TypeScript:
> src/graphql.schema.ts(11,5): error TS1244: Abstract methods can only appear within an abstract class.

## Expected behavior

Error must not be thrown on server start after _src/graphql.schema.ts_ update

## Minimal reproduction of the problem with instructions

https://github.com/biryukvy/nest-gql-abstract-method-issue 
(Changes, that have been added to reproduce the issue can be found in the commit: **87053d**) 

## What is the motivation / use case for changing the behavior?

It is needed to pass parameters to subqueries

## Environment

<pre><code>
Nest version: 5.5.0

 
For Tooling issues:
- Node version: 8.14.1  
- Platform: Linux Ubuntu 18.04 

Others:

</code></pre>

**Comment by Simonpedro** [comment]
I have the same problem

Given the following graphql type:

```graphql
type Image {
  url(options: ImageOptions): String!
}
```
Te result of the code generation process is:
```ts
export class Image {
    abstract url(options?: ImageOptions): string | Promise<string>;
}
```
An abstrat method cannot be defined in a concrete class so, the class should be generated in the following way:

```ts
export abstract class Image {
    abstract url(options?: ImageOptions): string | Promise<string>;
}
```



> 
> 
> What would be the desired output, I wonder? Would it be the following?
> 
> ```ts
> export class Cat {
>    food(brand?: string): Food[] | Promise<Food[]> {
>       throw new NotImplementedError();
>    }
> }
> ```

Well, the desired output would be:
```ts
export abstract class Cat {
   abstract food(brand?: string): Food[] | Promise<Food[]>;
}
```

**Comment by kamilmysliwiec** [comment]
It actually should be fixed in 5.5.0+

**Comment by biryukvy** [comment]
@kamilmysliwiec, For me, it is still reproducible, though I am using "@nestjs/graphql": "^5.5.1".  Could you check the minimal reproducible example, that I've provided in the issue description?

**Comment by kamilmysliwiec** [comment]
As far as I see, all methods are abstract (+ class is marked as abstract too) https://github.com/biryukvy/nest-gql-abstract-method-issue/blob/master/src/graphql.schema.ts

**Comment by biryukvy** [comment]
@kamilmysliwiec, the problem is not fixed, could you reopen the issue?

**Comment by vrozhkov** [comment]
@kamilmysliwiec, I have tried with nestjs v.5.5.0 and 5.6.0 - the issue is still present

**Comment by triedal** [comment]
Any workaround for this at the moment? Experience the same issue.

**Comment by Simonpedro** [comment]
I'm fixing manually everytime by the moment.

**Comment by triedal** [comment]
@Simonpedro how are you doing that? My manual changes in `graphql.schema.ts` are overwritten every time I restart the server bc it is autogenerated.

**Comment by triedal** [comment]
I think one way to work around this may be to change `outputAs` from `class` to `interface`. However, you would not be able to do any validation inside your DTO's.

**Comment by Simonpedro** [comment]
@triedal I just leave auto generation deactivated and turn it on after a change in queries or schema, an then fix the types manually. I'd be annoying to do this when the schema/queries are not stable but well 🤷

**Comment by triedal** [comment]
@Simonpedro thanks for the reply. My schema is changing pretty rapidly so I elected to switch everything over to interfaces which resolved the issue.
